# -*- coding: utf-8 -*-
"""sheril_copilot_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vJIEHib557yDTb_166N5gaEudlMrK3cz
"""

# Changement effectué depuis VS Code pour vérifier la chaîne VS Code > GitHub > Google Colab.
import os

# Commented out IPython magic to ensure Python compatibility.
# %%writefile config_parsers.py
# import re
# from bs4 import BeautifulSoup
# 
# def parse_evt(soup, tour_id):
#     dons_emis = []
#     messages = soup.find_all(class_="message")
#     if not messages:
#         lignes = soup.get_text().split("\n")
#     else:
#         lignes = [m.get_text() for m in messages]
# 
#     regex_argent = re.compile(r"Le commandant\s+(.+?)\s*\((\d+)\)\s+as?\s+transmis\s+([\d\s\.,\xA0]+)\s+au commandant\s+(.+?)\s*\((\d+)\)", re.IGNORECASE)
#     regex_tech = re.compile(r"Le commandant\s+(.+?)\s*\((\d+)\)\s+as?\s+transmis\s+la technologie\s+(.+?)\s+au commandant\s+(.+?)\s*\((\d+)\)", re.IGNORECASE)
# 
#     for ligne in lignes:
#         match_tech = regex_tech.search(ligne)
#         if match_tech:
#             nom_emetteur, id_emetteur, nom_tech, nom_receveur, id_receveur = match_tech.groups()
#             dons_emis.append({
#                 "emetteur": str(id_emetteur), "emetteur_nom": nom_emetteur.strip(),
#                 "receveur": str(id_receveur), "receveur_nom": nom_receveur.strip(),
#                 "montant": 1.0, "type_don": f"Technologie: {nom_tech.strip()}"
#             })
#             continue
# 
#         match_argent = regex_argent.search(ligne)
#         if match_argent:
#             nom_emetteur, id_emetteur, montant_str, nom_receveur, id_receveur = match_argent.groups()
#             montant_propre = montant_str.replace("\xa0", "").replace(" ", "").replace("\u202f", "").replace(",", ".")
#             try:
#                 montant = float(montant_propre)
#             except ValueError:
#                 montant = 0.0
# 
#             dons_emis.append({
#                 "emetteur": str(id_emetteur), "emetteur_nom": nom_emetteur.strip(),
#                 "receveur": str(id_receveur), "receveur_nom": nom_receveur.strip(),
#                 "montant": montant, "type_don": "Argent"
#             })
#     return {"dons_emis": dons_emis}
# 
# def parse_classement_generique(soup, tour_id):
#     resultats = {}
#     if not soup:
#         return resultats
# 
#     tables = soup.find_all("table")
#     for table in tables:
#         rows = table.find_all("tr")
#         for tr in rows[1:]:
#             cols = tr.find_all(["td", "th"])
#             if len(cols) < 3:
#                 continue
# 
#             jid = None
#             nom_brut = ""
#             race = "-"
#             valeur = 0.0
# 
#             for i, col in enumerate(cols):
#                 txt = col.get_text(strip=True)
#                 if txt.isdigit() and len(txt) <= 3 and i >= 2:
#                     jid = txt
#                 if txt in ["Atalantes", "Fergok", "Yoksor", "Zwaias", "Fremens", "Humain", "Cyborg"]:
#                     race = txt
# 
#             if not jid:
#                 for col in cols:
#                     span_num = col.find("span", class_="c6")
#                     if span_num and span_num.get_text(strip=True).isdigit():
#                         jid = span_num.get_text(strip=True)
#                         break
# 
#             if not jid:
#                 continue
# 
#             for col in cols[:2]:
#                 t = col.get_text(strip=True)
#                 if not t.isdigit() and len(t) > 1 and "---" not in t:
#                     nom_brut = re.sub(r'\s*\(\d+\)', '', t).strip()
#                     break
# 
#             for col in reversed(cols):
#                 txt = col.get_text(strip=True)
#                 if any(char.isdigit() for char in txt) and "%" not in txt:
#                     partie_principale = txt.split('(')[0]
#                     clean_t = re.sub(r'[^\d,\.-]', '', partie_principale.replace('\xa0', '').replace(' ', '').replace('\u202f', '').replace(',', '.'))
#                     if clean_t and clean_t not in ['.', '-', '+']:
#                         try:
#                             valeur = float(clean_t)
#                             break
#                         except ValueError:
#                             pass
# 
#             resultats[jid] = {
#                 "joueur_id": str(jid),
#                 "nom": nom_brut if nom_brut else f"ID:{jid}",
#                 "race": race,
#                 "valeur": float(valeur),
#                 "rang": 0,
#                 "variation": 0.0
#             }
#     return resultats
# 
# def parse_planetes(soup, tour_id):
#     resultats = {}
#     if not soup:
#         return resultats
# 
#     tables = soup.find_all("table")
#     for table in tables:
#         rows = table.find_all("tr")
#         for tr in rows[1:]:
#             cols = tr.find_all(["td", "th"])
#             if len(cols) < 5:
#                 continue
# 
#             nom_txt = cols[1].get_text(strip=True)
#             if "---" in nom_txt:
#                 continue
# 
#             numero_txt = cols[2].get_text(strip=True)
#             if not numero_txt.isdigit():
#                 continue
# 
#             jid = numero_txt
#             nom_brut = nom_txt
#             race = cols[3].get_text(strip=True)
# 
#             planetes_txt = cols[4].get_text(strip=True)
#             clean_planetes = re.sub(r'[^\d]', '', planetes_txt.split('(')[0])
#             nb_planetes = int(clean_planetes) if clean_planetes.isdigit() else 0
# 
#             resultats[jid] = {
#                 "joueur_id": str(jid),
#                 "nom": nom_brut,
#                 "race": race if race and race != "-" else "-",
#                 "planetes": nb_planetes
#             }
#     return resultats
# 
# def parse_combats(soup, tour_id):
#     """Parse le fichier combats.htm pour extraire les statistiques militaires par joueur."""
#     resultats = {}
#     if not soup:
#         return resultats
# 
#     tables = soup.find_all("table")
#     for table in tables:
#         rows = table.find_all("tr")
#         for tr in rows:
#             cols = tr.find_all(["td", "th"])
#             # On cherche les lignes de combat qui ont au moins 5 colonnes (Attaquant, Attaqué, Type, Flotte, Cible)
#             if len(cols) < 5:
#                 continue
# 
#             texte_col0 = cols[0].get_text()
#             texte_col1 = cols[1].get_text()
# 
#             # Extraction des IDs entre parenthèses via Regex (ex: "Imotep (8)" -> ID "8")
#             match_att = re.search(r'\((\d+)\)', texte_col0)
#             match_def = re.search(r'\((\d+)\)', texte_col1)
# 
#             if not match_att or not match_def:
#                 continue
# 
#             id_attaquant = match_att.group(1)
#             id_defenseur = match_def.group(1)
# 
#             # Analyse de la dernière colonne pour voir si une planète a été prise
#             texte_cible = cols[4].get_text(strip=True)
#             planete_prise = 0
#             if "aucune plan" not in texte_cible.lower() and "(" in texte_cible:
#                 # S'il y a des planètes listées entre parenthèses (ex: "(Tyqyeu 4)")
#                 match_planet_count = re.findall(r'\b[A-Za-zÀ-ÿ0-9]+\s+\d+\b', texte_cible)
#                 planete_prise = len(match_planet_count) if match_planet_count else 1
# 
#             # Initialisation des structures pour l'attaquant si besoin
#             if id_attaquant not in resultats:
#                 resultats[id_attaquant] = {
#                     "combats": {
#                         "attaques_lancees": 0,
#                         "attaques_subies": 0,
#                         "cibles_attaquees": [],
#                         "planetes_perdues_adversaire": 0
#                     }
#                 }
# 
#             # Initialisation des structures pour le défenseur si besoin
#             if id_defenseur not in resultats:
#                 resultats[id_defenseur] = {
#                     "combats": {
#                         "attaques_lancees": 0,
#                         "attaques_subies": 0,
#                         "cibles_attaquees": [],
#                         "planetes_perdues_adversaire": 0
#                     }
#                 }
# 
#             # Incrémentation des compteurs de l'attaquant
#             resultats[id_attaquant]["combats"]["attaques_lancees"] += 1
#             resultats[id_attaquant]["combats"]["planetes_perdues_adversaire"] += planete_prise
#             if id_defenseur not in resultats[id_attaquant]["combats"]["cibles_attaquees"]:
#                 resultats[id_attaquant]["combats"]["cibles_attaquees"].append(id_defenseur)
# 
#             # Incrémentation des compteurs du défenseur (attaques subies)
#             resultats[id_defenseur]["combats"]["attaques_subies"] += 1
# 
#     return resultats
# 
# def parse_alliances(soup, tour_id):
#     """Parse le fichier alliances.htm pour extraire l'alliance de chaque joueur."""
#     resultats = {}
#     if not soup:
#         return resultats
# 
#     tables = soup.find_all("table")
#     for table in tables:
#         rows = table.find_all("tr")
#         # On saute l'en-tête (première ligne)
#         for tr in rows[1:]:
#             cols = tr.find_all(["td", "th"])
#             if len(cols) < 5:
#                 continue
# 
#             # La colonne 1 (index 1) contient le nom de l'alliance
#             nom_alliance = cols[1].get_text(strip=True)
#             if not nom_alliance:
#                 continue
# 
#             # On cherche tous les spans de joueurs dans toute la ligne (concepteur + membres)
#             spans_joueurs = tr.find_all("span", class_=re.compile(r'^race\d+$'))
# 
#             for span in spans_joueurs:
#                 texte_span = span.get_text()  # Ex: "Rakshass (5)"
#                 match = re.search(r'\((\d+)\)', texte_span)
#                 if match:
#                     jid = match.group(1)
#                     # Un joueur peut techniquement appartenir à une alliance, on l'associe
#                     resultats[jid] = {"alliance": nom_alliance}
# 
#     return resultats
# 
# PARSERS_REGISTRY = {
#     "evt.htm": parse_evt,
#     "technologie.htm": parse_classement_generique,
#     "rayonnement.htm": parse_classement_generique,
#     "pop_vs.htm": parse_classement_generique,
#     "offensive.htm": parse_classement_generique,
#     "centaures.htm": parse_classement_generique,
#     "pop.htm": parse_classement_generique,
#     "puissance.htm": parse_classement_generique,
#     "reputation.htm": parse_classement_generique,
#     "planetes.htm": parse_planetes,
#     "combats.htm": parse_combats,
#     "alliances.htm": parse_alliances,
#     "alliance.htm": parse_alliances
# }

# Commented out IPython magic to ensure Python compatibility.
# %%writefile game_indicators.py
# import numpy as np
# 
# def enrichir_donnees_joueurs(joueurs_dict):
#     """
#     Enrichit le dictionnaire des joueurs avec des indicateurs relationnels,
#     militaires et calcule un score d'isolement géopolitique nuancé (0.0 à 1.0).
#     """
#     for jid, data in joueurs_dict.items():
#         if jid == "_dons_emis_tour":
#             continue
# 
#         combats = data.get("combats", {})
#         attaques_lancees = combats.get("attaques_lancees", 0)
#         attaques_subies = combats.get("attaques_subies", 0)
#         cibles = combats.get("cibles_attaquees", [])
# 
#         balance_projection = attaques_lancees - attaques_subies
#         total_engagements = attaques_lancees + attaques_subies
#         indice_tension = float(total_engagements) / max(1, data.get("planetes", 1))
# 
#         planetes_conquises = combats.get("planetes_perdues_adversaire", 0)
#         ratio_offensif = float(planetes_conquises) / max(1, attaques_lancees) if attaques_lancees > 0 else 0.0
# 
#         data["indicateurs_militaires"] = {
#             "balance_projection": int(balance_projection),
#             "attaques_lancees": int(attaques_lancees),
#             "attaques_subies": int(attaques_subies),
#             "cibles_attaquees": cibles,
#             "indice_tension": round(indice_tension, 3),
#             "ratio_offensif": round(ratio_offensif, 3)
#         }
# 
#         # Analyse géopolitique et score d'isolement nuancé
#         alliance = data.get("alliance", "Aucune")
#         dons = data.get("dons_recus", {})
#         nb_dons = dons.get("total_recu", 0)
# 
#         # Score d'isolement de base : 1.0 (totalement isolé) si aucune alliance
#         score_isolement = 1.0 if alliance == "Aucune" else 0.2
# 
#         # Réduction de l'isolement en fonction des interactions concrètes
#         facteur_connexions = len(cibles) * 0.15 + nb_dons * 0.2 + total_engagements * 0.05
#         score_isolement = max(0.0, min(1.0, score_isolement - facteur_connexions))
# 
#         # Si le joueur a des indices d'alliance secrète / multi-interactions (ex: attaques concertées)
#         if len(cibles) >= 2 and alliance == "Aucune":
#             score_isolement = round(max(0.3, min(0.6, score_isolement)), 2)
#         else:
#             score_isolement = round(score_isolement, 2)
# 
#         data["indicateurs_geopolitiques"] = {
#             "alliance": str(alliance),
#             "est_isole": score_isolement
#         }
# 
#     return joueurs_dict

import os
import json
import zipfile
import requests
import gspread
import importlib
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import google.generativeai as genai
from google.colab import auth, userdata
from sklearn.ensemble import IsolationForest

# 1. Authentification interactive Google Colab
auth.authenticate_user()
import google.auth
creds, _ = google.auth.default(
    scopes=['https://www.googleapis.com/auth/spreadsheets',
            'https://www.googleapis.com/auth/drive']
)
gc = gspread.authorize(creds)

# 2. Configuration des modules annexes
import config_parsers
importlib.reload(config_parsers)
from config_parsers import PARSERS_REGISTRY

import game_indicators
importlib.reload(game_indicators)
from game_indicators import enrichir_donnees_joueurs

SHEET_NAME = "Sheril_Copilot"
BASE_EXTRACT_DIR = "./extracted_game_data"
PREMIER_TOUR = 1
BASE_ZIP_URL = "https://sheril.pbem-france.net/stats/statsT{NUM}.zip"
DISCORD_WEBHOOK_URL = os.environ.get("DISCORD_WEBHOOK_URL", "https://discord.com/api/webhooks/1540810441402351706/Ph8kE6VVnlLKxkXwIEo_4Y7iMNNK9B0-P-WKsckOcbsInVN6UX_4ADIWtgZ3Mq3dqVEY")

SEUILS_COMPTEURS = {
    "cumul_technologies_donnees": [10, 25, 50, 100],
    "cumul_technologies_recues": [10, 25, 50, 100],
    "cumul_centaures_donnes": [10000, 50000, 100000],
    "cumul_centaures_recus": [10000, 50000, 100000],
    "cumul_planetes_prises": [10, 30, 50, 100],
    "cumul_planetes_perdues": [10, 30, 50, 100],
    "cumul_lieutenants_achetes": [10, 25, 50],
    "cumul_lieutenants_morts": [10, 30, 50],
    "cumul_centaures_depenses_lieutenants": [10000, 50000, 100000]
}

COMPTEURS_CUMULES = [
    "cumul_technologies_donnees", "cumul_technologies_recues",
    "cumul_centaures_donnes", "cumul_centaures_recus",
    "cumul_planetes_prises", "cumul_planetes_perdues",
    "cumul_lieutenants_achetes", "cumul_lieutenants_morts",
    "cumul_centaures_depenses_lieutenants"
]

STREAKS = [
    "streak_sans_attaque", "streak_avec_attaque", "streak_top1_pv_combat",
    "streak_acceleration_pop", "streak_acceleration_rayonnement",
    "streak_variation_planetes", "streak_variation_centaures",
    "streak_achat_lieutenant", "streak_don_public"
]

# Clé API Gemini
GEMINI_API_KEY = userdata.get("GEMINI_API_KEY")
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)
else:
    print("[Avertissement] Aucune clé API Gemini trouvée.")

def get_latest_turns_and_download():
    print("[Étape 0] Recherche incrémentale des tours disponibles...")
    session = requests.Session()
    session.headers.update({
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        "Referer": "https://sheril.pbem-france.net/"
    })

    tour_actuel = PREMIER_TOUR
    dernier_tour_trouve = None

    while True:
        url_zip = BASE_ZIP_URL.replace("{NUM}", str(tour_actuel))
        response = session.get(url_zip, allow_redirects=False)
        if response.status_code == 404 or not response.ok:
            break
        dernier_tour_trouve = tour_actuel
        tour_actuel += 1

    if not dernier_tour_trouve:
        return []

    print(f"[Étape 0] Dernier tour détecté -> Tour {dernier_tour_trouve}.")
    tours_a_traiter = list(range(PREMIER_TOUR, dernier_tour_trouve + 1))

    os.makedirs(BASE_EXTRACT_DIR, exist_ok=True)
    tours_valides = []

    for t in tours_a_traiter:
        url_zip = BASE_ZIP_URL.replace("{NUM}", str(t))
        response = session.get(url_zip)
        if response.ok:
            zip_filename = f"temp_tour_{t}.zip"
            with open(zip_filename, "wb") as f:
                f.write(response.content)

            tour_dir = os.path.join(BASE_EXTRACT_DIR, f"tour_{t}")
            os.makedirs(tour_dir, exist_ok=True)

            with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
                zip_ref.extractall(tour_dir)
            os.remove(zip_filename)
            tours_valides.append(t)

    return tours_valides

def parse_tour_files(tour_id):
    print(f"\n[Étape 1] Parsing complet du Tour {tour_id}...")
    joueurs_dict = {}
    tour_dir = os.path.join(BASE_EXTRACT_DIR, f"tour_{tour_id}")

    if not os.path.exists(tour_dir):
        return joueurs_dict

    for root, dirs, files in os.walk(tour_dir):
        for file in files:
            file_lower = file.lower()
            if file_lower not in PARSERS_REGISTRY:
                continue

            file_path = os.path.join(root, file)
            try:
                with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                    soup = BeautifulSoup(f.read(), 'html.parser')

                parser_func = PARSERS_REGISTRY[file_lower]
                metric_values = parser_func(soup, tour_id)

                if metric_values is None:
                    continue

                if file_lower == "evt.htm":
                    if isinstance(metric_values, dict) and "dons_emis" in metric_values:
                        for don in metric_values["dons_emis"]:
                            jid_emetteur = str(don.get("emetteur"))
                            if jid_emetteur and jid_emetteur != "None":
                                if jid_emetteur not in joueurs_dict:
                                    joueurs_dict[jid_emetteur] = init_player_structure(tour_id, jid_emetteur, don.get("emetteur_nom", "-"), "-")
                                if "dons_emis" not in joueurs_dict[jid_emetteur]:
                                    joueurs_dict[jid_emetteur]["dons_emis"] = []
                                joueurs_dict[jid_emetteur]["dons_emis"].append(don)
                                categorie_evenement = "dons"
                                if don.get("type_don") in ["Achat_Lieutenant", "Mort_Lieutenant"]:
                                    categorie_evenement = "lieutenants"
                                elif don.get("type_don") in ["Vol_Techno_Rate", "Cession_Planete"]:
                                    categorie_evenement = "alliances"
                                if don.get("type_don") == "Vol_Techno_Rate":
                                    evenement_emetteur = {
                                        "type": "vol_techno_rate", "role": "auteur",
                                        "cible": don.get("receveur_nom"), "status": don.get("status", "echec_intercepte")
                                    }
                                elif don.get("type_don") == "Cession_Planete":
                                    evenement_emetteur = {
                                        "type": "cession_planete", "role": "donneur",
                                        "beneficiaire": don.get("receveur_nom"), "systeme": don.get("systeme")
                                    }
                                    if "nombre" in don:
                                        evenement_emetteur["nombre"] = don["nombre"]
                                else:
                                    evenement_emetteur = don.copy()
                                joueurs_dict[jid_emetteur]["evenements_du_tour"][categorie_evenement].append(evenement_emetteur)
                                if don.get("type_don") in ["Vol_Techno_Rate", "Cession_Planete"]:
                                    joueurs_dict[jid_emetteur]["interactions_directes"] += 1
                                if don.get("type_don", "").startswith("Technologie:"):
                                    joueurs_dict[jid_emetteur]["cumul_technologies_donnees"] += 1
                                    jid_receveur = str(don.get("receveur"))
                                    if jid_receveur and jid_receveur != "None":
                                        if jid_receveur not in joueurs_dict:
                                            joueurs_dict[jid_receveur] = init_player_structure(
                                                tour_id, jid_receveur, don.get("receveur_nom", "-"), "-"
                                            )
                                        joueurs_dict[jid_receveur]["cumul_technologies_recues"] += 1
                                        joueurs_dict[jid_receveur]["evenements_du_tour"]["dons"].append({**don, "role": "receveur"})
                                        joueurs_dict[jid_receveur]["interactions_directes"] += 1
                                elif don.get("type_don") == "Centaures":
                                    joueurs_dict[jid_emetteur]["cumul_centaures_donnes"] += float(don.get("montant", 0.0))
                                    jid_receveur = str(don.get("receveur"))
                                    if jid_receveur and jid_receveur != "None":
                                        if jid_receveur not in joueurs_dict:
                                            joueurs_dict[jid_receveur] = init_player_structure(
                                                tour_id, jid_receveur, don.get("receveur_nom", "-"), "-"
                                            )
                                        joueurs_dict[jid_receveur]["cumul_centaures_recus"] += float(don.get("montant", 0.0))
                                        joueurs_dict[jid_receveur]["evenements_du_tour"]["dons"].append({**don, "role": "receveur"})
                                        joueurs_dict[jid_receveur]["interactions_directes"] += 1
                                elif don.get("type_don") == "Vol_Techno_Rate":
                                    jid_cible = str(don.get("receveur"))
                                    if jid_cible and jid_cible != "None":
                                        if jid_cible not in joueurs_dict:
                                            joueurs_dict[jid_cible] = init_player_structure(tour_id, jid_cible, don.get("receveur_nom", "-"), "-")
                                        joueurs_dict[jid_cible]["evenements_du_tour"]["alliances"].append({
                                            "type": "vol_techno_rate", "role": "cible", "auteur": don.get("emetteur_nom"),
                                            "status": don.get("status", "echec_intercepte")
                                        })
                                        joueurs_dict[jid_cible]["interactions_directes"] += 1
                                elif don.get("type_don") == "Cession_Planete":
                                    jid_receveur = str(don.get("receveur"))
                                    if jid_receveur and jid_receveur != "None":
                                        if jid_receveur not in joueurs_dict:
                                            joueurs_dict[jid_receveur] = init_player_structure(tour_id, jid_receveur, don.get("receveur_nom", "-"), "-")
                                        joueurs_dict[jid_receveur]["evenements_du_tour"]["alliances"].append({
                                            "type": "cession_planete", "role": "receveur", "donneur": don.get("emetteur_nom"),
                                            "systeme": don.get("systeme")
                                            , **({"nombre": don["nombre"]} if "nombre" in don else {})
                                        })
                                        joueurs_dict[jid_receveur]["interactions_directes"] += 1
                                elif don.get("type_don") == "Achat_Lieutenant":
                                    joueurs_dict[jid_emetteur]["cumul_lieutenants_achetes"] += 1
                                    joueurs_dict[jid_emetteur]["cumul_centaures_depenses_lieutenants"] += float(don.get("montant", 0.0))
                                elif don.get("type_don") == "Mort_Lieutenant":
                                    joueurs_dict[jid_emetteur]["cumul_lieutenants_morts"] += 1
                    continue

                for jid, r in metric_values.items():
                    jid = str(r.get("joueur_id", jid))
                    if jid not in joueurs_dict:
                        joueurs_dict[jid] = init_player_structure(tour_id, jid, r.get("nom", "-"), r.get("race", "-"))

                    if file_lower == "planetes.htm":
                        joueurs_dict[jid]["planetes"] = int(r.get("planetes", 0))
                    elif file_lower == "centaures.htm":
                        joueurs_dict[jid]["centaures"] = float(r.get("valeur", 0.0))
                    elif file_lower == "pop.htm":
                        joueurs_dict[jid]["pop"] = float(r.get("valeur", 0.0))
                    elif file_lower == "puissance.htm":
                        joueurs_dict[jid]["puissance"] = float(r.get("valeur", 0.0))
                    elif file_lower == "reputation.htm":
                        joueurs_dict[jid]["reputation"] = float(r.get("valeur", 0.0))
                    elif file_lower == "technologie.htm":
                        joueurs_dict[jid]["tech_points"] = float(r.get("valeur", 0.0))
                    elif file_lower == "rayonnement.htm":
                        joueurs_dict[jid]["rayonnement_pts"] = float(r.get("valeur", 0.0))
                    elif file_lower == "pop_vs.htm":
                        joueurs_dict[jid]["popvs_pts"] = float(r.get("valeur", 0.0))
                    elif file_lower == "offensive.htm":
                        joueurs_dict[jid]["offensive_pts"] = float(r.get("valeur", 0.0))
                    elif file_lower == "combats.htm":
                        if "combats" in r:
                            joueurs_dict[jid]["combats"] = r["combats"]
                            joueurs_dict[jid]["cumul_planetes_prises"] = int(r["combats"].get("planetes_prises", 0))
                            joueurs_dict[jid]["cumul_planetes_perdues"] = int(r["combats"].get("planetes_perdues", 0))
                            joueurs_dict[jid]["evenements_du_tour"]["combats"].extend(
                                r["combats"].get("evenements", [])
                            )
                    elif file_lower in ["alliances.htm", "alliance.htm"]:
                        if "alliance" in r:
                            joueurs_dict[jid]["alliance"] = str(r["alliance"])

                    if r.get("nom", "-") not in ["-", ""]:
                        joueurs_dict[jid]["nom"] = r["nom"]
                    if r.get("race", "-") not in ["-", ""]:
                        joueurs_dict[jid]["race"] = r["race"]
            except Exception as e:
                print(f"[Diag-Parsing] Erreur sur '{file}' (Tour {tour_id}) : {e}")

    return joueurs_dict

def init_player_structure(tour_id, jid, nom, race):
    return {
        "tour_id": int(tour_id), "joueur_id": str(jid), "nom": nom, "race": race,
        "planetes": 0, "centaures": 0.0, "pop": 0.0, "puissance": 0.0, "reputation": 0.0,
        "tech_points": 0.0, "rayonnement_pts": 0.0, "popvs_pts": 0.0, "offensive_pts": 0.0,
        "alliance": "Aucune", "combats": {}, "dons_emis": [],
        "cumul_technologies_donnees": 0, "cumul_technologies_recues": 0,
        "cumul_centaures_donnes": 0.0, "cumul_centaures_recus": 0.0,
        "cumul_planetes_prises": 0, "cumul_planetes_perdues": 0,
        "cumul_lieutenants_achetes": 0, "cumul_lieutenants_morts": 0,
        "cumul_centaures_depenses_lieutenants": 0.0,
        "dons_recus": {}, "classements": {}, "indicateurs_derives": {},
        "evenements_du_tour": {"combats": [], "dons": [], "lieutenants": [], "alliances": []},
        "interactions_directes": 0, "streaks": {}
    }


def calculer_streaks(historique_tours_dict, jid, tour_actuel):
    """Calcule les séries en cours pour un joueur à partir de l'historique brut."""
    tours = sorted(historique_tours_dict)
    if not tours:
        return {}

    def valeur(tour_id, cle, default=0):
        return historique_tours_dict[tour_id].get(jid, {}).get(cle, default)

    def longueur_condition(condition):
        longueur = 0
        for index in range(len(tours) - 1, -1, -1):
            if condition(index):
                longueur += 1
            else:
                break
        return longueur

    def variation(index, cle):
        if index == 0:
            return 0.0
        return float(valeur(tours[index], cle, 0.0) - valeur(tours[index - 1], cle, 0.0))

    def streak_variation(cle):
        derniere = variation(len(tours) - 1, cle)
        if derniere == 0:
            return 0, None
        direction = 1 if derniere > 0 else -1
        longueur = 0
        for index in range(len(tours) - 1, 0, -1):
            delta = variation(index, cle)
            if delta == 0 or (delta > 0) != (direction > 0):
                break
            longueur += 1
        return longueur, "hausse" if direction > 0 else "baisse"

    streak_planetes, direction_planetes = streak_variation("planetes")
    streak_centaures, direction_centaures = streak_variation("centaures")

    streaks = {
        "streak_sans_attaque": longueur_condition(
            lambda index: sum(valeur(tours[index], "combats", {}).get(key, 0) for key in ("attaques_lancees", "attaques_subies")) == 0
        ),
        "streak_avec_attaque": longueur_condition(
            lambda index: sum(valeur(tours[index], "combats", {}).get(key, 0) for key in ("attaques_lancees", "attaques_subies")) > 0
        ),
        "streak_achat_lieutenant": longueur_condition(
            lambda index: valeur(tours[index], "cumul_lieutenants_achetes", 0) > 0
        ),
        "streak_don_public": longueur_condition(
            lambda index: valeur(tours[index], "cumul_centaures_donnes", 0) > 0
            or valeur(tours[index], "cumul_technologies_donnees", 0) > 0
        ),
        "streak_variation_planetes": streak_planetes,
        "streak_variation_centaures": streak_centaures,
        "streak_variation_planetes_tendance": direction_planetes,
        "streak_variation_centaures_tendance": direction_centaures
    }

    def seconde_variation(index, cle):
        if index < 2:
            return 0.0
        return variation(index, cle) - variation(index - 1, cle)

    for nom_streak, cle in (
        ("streak_acceleration_pop", "pop"),
        ("streak_acceleration_rayonnement", "rayonnement_pts")
    ):
        derniere = seconde_variation(len(tours) - 1, cle)
        direction = 1 if derniere > 0 else -1 if derniere < 0 else 0
        streaks[nom_streak] = longueur_condition(
            lambda index, cle=cle, direction=direction: direction != 0
            and seconde_variation(index, cle) * direction > 0
        )

    variations_puissance = {}
    for index, tour_id in enumerate(tours):
        for joueur_id in historique_tours_dict[tour_id]:
            if index > 0:
                variations_puissance[joueur_id, tour_id] = (
                    float(historique_tours_dict[tour_id].get(joueur_id, {}).get("puissance", 0.0))
                    - float(historique_tours_dict[tours[index - 1]].get(joueur_id, {}).get("puissance", 0.0))
                )

    top1_par_tour = {}
    for index, tour_id in enumerate(tours):
        if index == 0:
            continue
        candidats = {
            joueur_id: variations_puissance.get((joueur_id, tour_id), 0.0)
            for joueur_id in historique_tours_dict[tour_id]
        }
        if candidats:
            top1_par_tour[tour_id] = max(candidats, key=candidats.get)
    streaks["streak_top1_pv_combat"] = longueur_condition(
        lambda index: tours[index] in top1_par_tour and top1_par_tour[tours[index]] == jid
    )

    return streaks


def construire_matrice_relations_historiques(historique_tours_dict):
    """Agrège toutes les relations dirigées enregistrées depuis le premier tour."""
    relations = {}
    noms_joueurs = {}
    total_tours = len(historique_tours_dict)

    def relation(jid_a, jid_b):
        if jid_a == jid_b:
            return None
        cle = tuple(sorted((str(jid_a), str(jid_b))))
        return relations.setdefault(cle, {
            "combats_donnes": 0,
            "combats_subis": 0,
            "ressources_donnees": 0.0,
            "tours_actifs": set()
        })

    for tour_id, joueurs in sorted(historique_tours_dict.items()):
        for jid, data in joueurs.items():
            jid = str(jid)
            nom = data.get("nom")
            if nom and nom != "-":
                noms_joueurs[jid] = nom

        for jid, data in joueurs.items():
            jid = str(jid)
            combats = data.get("combats", {})
            for cible_id in combats.get("cibles_attaquees", []):
                cible_id = str(cible_id)
                rel = relation(jid, cible_id)
                if rel is None:
                    continue
                joueur_1, joueur_2 = sorted((jid, cible_id))
                if jid == joueur_1:
                    rel["combats_donnes"] += 1
                else:
                    rel["combats_subis"] += 1
                rel["tours_actifs"].add(tour_id)

            for don in data.get("dons_emis", []):
                receveur = don.get("receveur")
                if receveur is None:
                    continue
                receveur = str(receveur)
                rel = relation(jid, receveur)
                if rel is None:
                    continue
                montant = don.get("montant", 0.0)
                if don.get("type_don", "").startswith("Technologie:"):
                    montant = 1.0
                elif don.get("type_don") == "Cession_Planete":
                    montant = float(don.get("nombre", 1))
                try:
                    rel["ressources_donnees"] += float(montant)
                except (TypeError, ValueError):
                    pass
                rel["tours_actifs"].add(tour_id)

    def frequence(relation_data):
        interactions = (
            relation_data["combats_donnes"]
            + relation_data["combats_subis"]
            + relation_data["ressources_donnees"]
        )
        tours_actifs = len(relation_data["tours_actifs"])
        ratio_tours = tours_actifs / max(1, total_tours)
        if ratio_tours >= 0.75 or interactions >= max(10, total_tours * 2):
            return "systématique"
        if ratio_tours >= 0.5 or interactions >= max(5, total_tours):
            return "élevée"
        if ratio_tours >= 0.25 or interactions >= 3:
            return "régulière"
        if interactions >= 2:
            return "occasionnelle"
        return "rare"

    matrice = []
    for (jid_1, jid_2), relation_data in sorted(relations.items()):
        matrice.append({
            "joueur_1": noms_joueurs.get(jid_1, f"Joueur #{jid_1}"),
            "joueur_2": noms_joueurs.get(jid_2, f"Joueur #{jid_2}"),
            "combats_donnes": relation_data["combats_donnes"],
            "combats_subis": relation_data["combats_subis"],
            "ressources_donnees": round(relation_data["ressources_donnees"], 3),
            "frequence_relation": frequence(relation_data)
        })
    return matrice


def detecter_indices_complots_suspects(historique_tours_dict):
    """Détecte les convergences militaires, flux suspects et recoupements."""
    tours = sorted(historique_tours_dict)
    if not tours:
        return []

    noms = {}
    attaques = []
    flux = {}

    def nom_joueur(jid):
        return noms.get(str(jid), f"Joueur #{jid}")

    def seuil_flux(nombre_dons, tours_actifs, volume, total_tours):
        ratio = tours_actifs / max(1, total_tours)
        if nombre_dons >= 10 or (nombre_dons >= 5 and ratio >= 0.5) or volume >= 50000:
            return "critique"
        if nombre_dons >= 6 or (nombre_dons >= 3 and ratio >= 0.4) or volume >= 20000:
            return "élevé"
        if nombre_dons >= 3 or ratio >= 0.25 or volume >= 5000:
            return "modéré"
        return "faible"

    for tour_id in tours:
        joueurs = historique_tours_dict[tour_id]
        for jid, data in joueurs.items():
            jid = str(jid)
            noms[jid] = data.get("nom", f"Joueur #{jid}")
            for cible_id in data.get("combats", {}).get("cibles_attaquees", []):
                attaques.append((tour_id, jid, str(cible_id)))

            for don in data.get("dons_emis", []):
                if don.get("type_don", "").startswith("Technologie:"):
                    volume = 1.0
                elif don.get("type_don") == "Centaures":
                    volume = float(don.get("montant", 0.0))
                elif don.get("type_don") == "Cession_Planete":
                    volume = float(don.get("nombre", 1))
                else:
                    continue
                receveur = don.get("receveur")
                if receveur is None or str(receveur) == jid:
                    continue
                cle = (jid, str(receveur))
                donnees_flux = flux.setdefault(cle, {"dons": 0, "volume": 0.0, "tours": set()})
                donnees_flux["dons"] += 1
                donnees_flux["volume"] += volume
                donnees_flux["tours"].add(tour_id)

    alertes = []

    tours_observes = tours[-3:] if len(tours) >= 3 else tours
    attaques_fenetre = [attaque for attaque in attaques if attaque[0] in tours_observes]
    cibles_par_attaquant = {}
    for tour_id, attaquant, cible in attaques_fenetre:
        cibles_par_attaquant.setdefault(attaquant, {}).setdefault(cible, set()).add(tour_id)

    convergences = {}
    for attaquant, cibles in cibles_par_attaquant.items():
        if any(
            historique_tours_dict[tour_id].get(attaquant, {}).get("alliance", "Aucune") != "Aucune"
            for tour_id in tours_observes
        ):
            continue
        for cible, tours_cibles in cibles.items():
            convergences.setdefault(("joueur", cible), {}).setdefault(attaquant, set()).update(tours_cibles)
            for tour_id in tours_observes:
                alliance = historique_tours_dict[tour_id].get(cible, {}).get("alliance", "Aucune")
                if alliance != "Aucune":
                    convergences.setdefault(("alliance", alliance), {}).setdefault(attaquant, set()).update(tours_cibles)

    for (type_cible, cible), attaquants in convergences.items():
        participants = [jid for jid, tours_cibles in attaquants.items() if len(tours_cibles) >= len(tours_observes)]
        if len(participants) < 2:
            continue
        if type_cible == "alliance":
            cible_texte = f"les membres de l'alliance publique '{cible}'"
        else:
            cible_texte = f"le commandant {nom_joueur(cible)}"
        alertes.append({
            "type_alerte": "Convergence d'agression sur une même alliance" if type_cible == "alliance" else "Convergence d'agression sur un même commandant",
            "seuil_alerte": "élevé" if len(participants) >= 3 else "modéré",
            "attaquants": [nom_joueur(jid) for jid in participants],
            "cible": nom_joueur(cible) if type_cible == "joueur" else cible,
            "tours_observes": len(tours_observes),
            "description": f"Ces commandants sans lien officiel attaquent {cible_texte} depuis {len(tours_observes)} tour(s)."
        })

    alertes_transactions = []
    for (donneur, receveur), donnees in flux.items():
        seuil = seuil_flux(donnees["dons"], len(donnees["tours"]), donnees["volume"], len(tours))
        if donnees["dons"] < 3 and donnees["volume"] < 5000:
            continue
        alertes_transactions.append({
            "type_alerte": "Transaction occulte",
            "seuil_alerte": seuil,
            "membres_soupconnes": [nom_joueur(donneur), nom_joueur(receveur)],
            "nombre_dons": donnees["dons"],
            "tours_actifs": len(donnees["tours"]),
            "volume_total": round(donnees["volume"], 3),
            "description": (
                f"{nom_joueur(donneur)} transfère régulièrement des ressources à {nom_joueur(receveur)} "
                f"sur {len(donnees['tours'])} tour(s), pour un volume cumulé de {round(donnees['volume'], 3)}."
            )
        })
    alertes.extend(alertes_transactions)

    cibles_communes = {}
    for (donneur, receveur), donnees in flux.items():
        if donneur > receveur:
            continue
        cibles_donneur = {cible for _, attaquant, cible in attaques_fenetre if attaquant == donneur}
        cibles_receveur = {cible for _, attaquant, cible in attaques_fenetre if attaquant == receveur}
        cibles_communes[(donneur, receveur)] = cibles_donneur & cibles_receveur
    for (donneur, receveur), cibles in cibles_communes.items():
        if not cibles:
            continue
        donnees = flux[(donneur, receveur)]
        alertes.append({
            "type_alerte": "Alliance secrète suspectée",
            "seuil_alerte": seuil_flux(donnees["dons"], len(donnees["tours"]), donnees["volume"], len(tours)),
            "membres_soupconnes": [nom_joueur(donneur), nom_joueur(receveur)],
            "cibles_communes": [nom_joueur(cible) for cible in sorted(cibles)],
            "description": (
                f"Ces deux commandants affichent un historique de dons répétés, tout en coordonnant "
                f"leurs attaques sur des cibles communes au cours des {len(tours_observes)} derniers tours."
            )
        })
    return alertes

def compiler_indicateurs_avances_et_seuils(historique_tours_dict):
    print("[Étape 2] Calcul des indicateurs dérivés et enrichissement militaire/géopolitique...")
    lignes_globales = []
    for tour_id, j_dict in historique_tours_dict.items():
        for jid, data in j_dict.items():
            puis = float(data.get("puissance", 0.0))
            pop = float(data.get("pop", 0.0))
            cent = float(data.get("centaures", 0.0))
            impact_val = puis - pop - cent

            lignes_globales.append({
                "tour_id": int(tour_id), "joueur_id": str(jid),
                "nom": data.get("nom"), "race": data.get("race"),
                "planetes": int(data.get("planetes", 0)), "centaures": cent,
                "pop": pop, "puissance": puis, "reputation": float(data.get("reputation", 0.0)),
                "tech_valeur": float(data.get("tech_points", 0.0)),
                "rayonnement_pts": float(data.get("rayonnement_pts", 0.0)),
                "popvs_pts": float(data.get("popvs_pts", 0.0)),
                "offensive_valeur": float(data.get("offensive_pts", 0.0)), "impact": impact_val
            })

    dernier_tour_id = max(historique_tours_dict.keys())
    dernier_tour_dict = historique_tours_dict[dernier_tour_id]
    compteurs_cumules = {}
    cumuls_par_tour = {}
    for tour_id, tour_dict in sorted(historique_tours_dict.items()):
        for jid, data in tour_dict.items():
            compteurs = compteurs_cumules.setdefault(jid, {})
            for nom_compteur in [
                "cumul_technologies_donnees", "cumul_technologies_recues",
                "cumul_centaures_donnes", "cumul_centaures_recus",
                "cumul_planetes_prises", "cumul_planetes_perdues",
                "cumul_lieutenants_achetes", "cumul_lieutenants_morts",
                "cumul_centaures_depenses_lieutenants"
            ]:
                compteurs[nom_compteur] = compteurs.get(nom_compteur, 0) + data.get(nom_compteur, 0)
        cumuls_par_tour[tour_id] = {
            jid: valeurs.copy() for jid, valeurs in compteurs_cumules.items()
        }

    tours_tries = sorted(cumuls_par_tour)
    seuils_par_joueur = {jid: [] for jid in dernier_tour_dict}
    if len(tours_tries) >= 2:
        tour_precedent = cumuls_par_tour[tours_tries[-2]]
        tour_actuel = cumuls_par_tour[tours_tries[-1]]
        for jid, compteurs_actuels in tour_actuel.items():
            compteurs_precedents = tour_precedent.get(jid, {})
            for nom_compteur, seuils in SEUILS_COMPTEURS.items():
                ancienne_valeur = compteurs_precedents.get(nom_compteur, 0)
                nouvelle_valeur = compteurs_actuels.get(nom_compteur, 0)
                for seuil in seuils:
                    if ancienne_valeur < seuil <= nouvelle_valeur:
                        seuils_par_joueur.setdefault(jid, []).append({
                            "compteur": nom_compteur,
                            "seuil": seuil,
                            "ancienne_valeur": ancienne_valeur,
                            "nouvelle_valeur": nouvelle_valeur,
                            "libelle": f"Seuil {seuil} atteint pour {nom_compteur}"
                        })

    for jid, data in dernier_tour_dict.items():
        data.update(compteurs_cumules.get(jid, {}))
        data["seuils_franchis"] = seuils_par_joueur.get(jid, [])
        data["streaks"] = calculer_streaks(historique_tours_dict, jid, dernier_tour_id)

    df = pd.DataFrame(lignes_globales)
    if df.empty:
        return dernier_tour_dict

    metriques_cibles = ["puissance", "planetes", "pop", "centaures", "reputation", "tech_valeur", "rayonnement_pts", "popvs_pts", "offensive_valeur", "impact"]
    moyennes_globales = {m: float(df[df["tour_id"] == dernier_tour_id][m].mean()) for m in metriques_cibles}

    for jid, data_p in dernier_tour_dict.items():
        df_j = df[df["joueur_id"] == jid].sort_values("tour_id")
        metriques_calc = {}
        if not df_j.empty:
            for m in metriques_cibles:
                valeurs_s = df_j[m].values
                progression = float(valeurs_s[-1] - valeurs_s[-2]) if len(valeurs_s) > 1 else 0.0
                derivee_prog = float(valeurs_s[-1] - 2 * valeurs_s[-2] + valeurs_s[-3]) if len(valeurs_s) > 2 else 0.0
                ecart_type = float(np.std(valeurs_s)) if len(valeurs_s) > 1 else 0.0
                ecart_moyenne = float(valeurs_s[-1] - moyennes_globales[m])
                ath = float(np.max(valeurs_s))
                atl = float(np.min(valeurs_s))
                tours_haut = int(sum(valeurs_s > moyennes_globales[m]))

                metriques_calc[m] = {
                    "progression": progression, "derivee_progression": derivee_prog,
                    "ecart_type": ecart_type, "ecart_moyenne": ecart_moyenne,
                    "all_time_high": ath, "all_time_low": atl, "tours_consecutifs_haut": tours_haut
                }
            data_p["indicateurs_derives"] = metriques_calc

            p_prog = metriques_calc["puissance"]["progression"]
            p_ecart = metriques_calc["puissance"]["ecart_moyenne"]
            tech_prog = metriques_calc["tech_valeur"]["progression"]
            off_val = data_p.get("offensive_pts", 0.0)

            if p_prog < 0 or (p_ecart < -100 and p_prog <= 0):
                statut_alerte = "en déclin"
            elif p_ecart > 200 and (tech_prog > 0 or off_val > 50):
                statut_alerte = "dominant"
            elif p_prog > 0 and (tech_prog > 0 or off_val > 20):
                statut_alerte = "menaçant"
            else:
                statut_alerte = "stable"

            data_p["stat_alerte"] = statut_alerte

    return enrichir_donnees_joueurs(dernier_tour_dict)



import pandas as pd
from sklearn.ensemble import IsolationForest

def generer_structs_json_joueurs_avancees(dernier_tour_dict):
    print("\n--- [DEBUG] Début de l'analyse avancée des outliers ---")
    joueurs_json_list = []

    def variation(data, metrique):
        return float(data.get("indicateurs_derives", {}).get(metrique, {}).get("progression", 0.0))

    def rang(metrique):
        valeurs = sorted(
            ((float(data.get(metrique, 0.0)), jid) for jid, data in dernier_tour_dict.items()),
            reverse=True
        )
        return {jid: index + 1 for index, (_, jid) in enumerate(valeurs)}

    rang_puissance = rang("puissance")
    rang_technologie = rang("tech_points")
    compteurs = list(COMPTEURS_CUMULES)
    moyennes_compteurs = {
        compteur: float(np.mean([data.get(compteur, 0) for data in dernier_tour_dict.values()]))
        for compteur in compteurs
    }

    def nettoyer(valeur):
        if isinstance(valeur, dict):
            return {
                cle: nettoyee for cle, item in valeur.items()
                if (nettoyee := nettoyer(item)) not in (None, {}, [], "")
            }
        if isinstance(valeur, list):
            return [item for item in (nettoyer(item) for item in valeur) if item not in (None, {}, [], "")]
        return valeur

    # Étape A : Transformation des indicateurs dérivés en DataFrame pour analyse globale
    lignes_analyse = []
    for jid, data in dernier_tour_dict.items():
        nom = data.get("nom", "Inconnu")
        ind_derives = data.get("indicateurs_derives", {})
        row = {"joueur_id": jid, "nom": nom, "race": data.get("race", "-")}

        for metrique, stats in ind_derives.items():
            row[f"{metrique}_prog"] = stats.get("progression", 0.0)
            row[f"{metrique}_ecart"] = stats.get("ecart_moyenne", 0.0)
            row[f"{metrique}_ath"] = stats.get("all_time_high", 0.0)
            row[f"{metrique}_derivee"] = stats.get("derivee_progression", 0.0)
        lignes_analyse.append(row)

    df_outliers = pd.DataFrame(lignes_analyse)
    print(f"[DEBUG] DataFrame d'analyse construit avec {len(df_outliers)} joueurs et {len(df_outliers.columns)} colonnes.")

    # Étape B : Utilisation d'un Isolation Forest si le nombre de joueurs est suffisant
    anomalies_ids = set()
    if len(df_outliers) > 3:
        features_cols = [c for c in df_outliers.columns if c not in ["joueur_id", "nom", "race"]]
        X = df_outliers[features_cols].fillna(0)

        iso = IsolationForest(contamination=0.15, random_state=42)
        df_outliers["is_anomaly"] = iso.fit_predict(X)

        anomalies_df = df_outliers[df_outliers["is_anomaly"] == -1]
        anomalies_ids = set(anomalies_df["joueur_id"])

        print(f"[DEBUG] Isolation Forest a détecté {len(anomalies_ids)} anomalie(s) globale(s).")
    else:
        print("[DEBUG] Pas assez de joueurs pour exécuter Isolation Forest (<= 3).")

    # Étape C : Construction du JSON final par joueur incluant tous les indicateurs avancés
    for jid, data in dernier_tour_dict.items():
        nom = data.get("nom", "Inconnu")
        race = data.get("race", "-")
        ind_derives = data.get("indicateurs_derives", {})

        print(f"\n[DEBUG] Analyse du joueur : {nom}")
        outliers = []

        for metrique, stats in ind_derives.items():
            prog = stats.get("progression", 0.0)
            ecart = stats.get("ecart_moyenne", 0.0)
            derivee = stats.get("derivee_progression", 0.0)
            ath = stats.get("all_time_high", 0.0)
            tours_haut = stats.get("tours_haut", [])

            # 1. Progression brute significative
            if abs(prog) > 50:
                signe = "+" if prog > 0 else ""
                outliers.append(f"{signe}{int(prog)} {metrique} (Progression tour actuel)")

            # 2. Écart massif par rapport à la moyenne du groupe
            if abs(ecart) > 150:
                signe = "+" if ecart > 0 else ""
                outliers.append(f"{signe}{int(ecart)} {metrique} (Écart structurel vs moyenne)")

            # 3. Dérivée (accélération ou freinage brutal)
            if abs(derivee) > 30:
                signe = "+" if derivee > 0 else ""
                outliers.append(f"Cassure/Accélération {metrique} (Dérivée: {signe}{int(derivee)})")

            # 4. All-Time High / Records historiques ou Tours Haut
            if ath != 0 and abs(prog) > 0 and (prog >= ath * 0.95):
                outliers.append(f"Record historique approché/battu pour {metrique} (ATH: {int(ath)})")
            elif tours_haut:
                # Si le joueur truste les sommets historiques
                outliers.append(f"Habitué des sommets sur {metrique} (Tours hauts enregistrés)")

        if jid in anomalies_ids:
            outliers.append("Profil global atypique (Détecté par IA multi-critères)")

        # Dédoublonnage et limitation pour garder l'essence narrative
        outliers = list(dict.fromkeys(outliers))[:5]
        print(f"  => Total outliers retenus pour {nom} : {len(outliers)}")

        # --- MODIFICATION ICI : Conversion des ID cibles en Noms ---
        cibles_brutes = data.get("combats", {}).get("cibles_attaquees", [])
        combats_recus = []
        for cible_id in cibles_brutes:
            nom_cible = dernier_tour_dict.get(str(cible_id), {}).get("nom", f"Joueur #{cible_id}")
            combats_recus.append(f"Cible attaquée : {nom_cible}")
        # -------------------------------------------------------------

        dons_financiers = [f"A versé un don vers {don.get('receveur_nom', 'inconnu')}" for don in data.get("dons_emis", [])]

        indicateurs_clefs = {
            "planetes": {
                "valeur": int(data.get("planetes", 0)),
                "variation": variation(data, "planetes")
            },
            "puissance": {
                "valeur": float(data.get("puissance", 0.0)),
                "variation": variation(data, "puissance"),
                "rang": rang_puissance.get(jid)
            },
            "score_technologique": {
                "valeur": float(data.get("tech_points", 0.0)),
                "variation": variation(data, "tech_valeur"),
                "rang": rang_technologie.get(jid)
            },
            "impact": {
                "valeur": int(data.get("puissance", 0) - data.get("pop", 0) - data.get("centaures", 0)),
                "variation": variation(data, "impact")
            }
        }
        for indicateur in indicateurs_clefs.values():
            indicateur["variation_formatee"] = f"{indicateur['variation']:+g}"

        compteurs_marquants = sorted(
            (
                {
                    "nom": compteur,
                    "valeur": data.get(compteur, 0),
                    "ecart_moyenne": data.get(compteur, 0) - moyennes_compteurs[compteur]
                }
                for compteur in compteurs
            ),
            key=lambda item: abs(item["ecart_moyenne"]),
            reverse=True
        )[:5]
        series_encours = sorted(
            (
                {
                    "nom": nom,
                    "longueur": longueur,
                    **({"tendance": data["streaks"].get(f"{nom}_tendance")} if nom in ["streak_variation_planetes", "streak_variation_centaures"] else {})
                }
                for nom, longueur in data.get("streaks", {}).items()
                if nom in STREAKS and isinstance(longueur, (int, float)) and longueur > 0
            ),
            key=lambda item: item["longueur"],
            reverse=True
        )[:3]

        structure_joueur = {
            "joueur": nom,
            "race": race,
            "alliance": data.get("indicateurs_geopolitiques", {}).get("alliance", data.get("alliance", "Aucune")),
            "isolement": float(data.get("indicateurs_geopolitiques", {}).get("est_isole", 1.0)),
            "indicateurs_clefs": indicateurs_clefs,
            "fait_marquant_outliers": outliers,
            "evenements_du_tour": data.get("evenements_du_tour", []),
            "historique_et_seuils": {
                "seuils_franchis_ce_tour": data.get("seuils_franchis", []),
                "compteurs_marquants": compteurs_marquants,
                "series_encours": series_encours
            },
        }
        joueurs_json_list.append(nettoyer(structure_joueur))

    print("\n--- [DEBUG] Fin de l'analyse avancée ---\n")
    return joueurs_json_list

# ==========================================
# APPEL IA AVEC PROMPT PÉDAGOGIQUE INTÉGRÉ
# ==========================================
def generer_gazette_ia(joueurs_json_str, tour_id):
    if not GEMINI_API_KEY:
        print("[IA] Clé API Gemini manquante.")
        return "📰 **Gazette (Fallback)**"

    print(f"[IA] Génération de la gazette pour le Tour {tour_id} à partir du JSON...")
    model = genai.GenerativeModel('gemini-3.6-flash') # Modèle actif standardisé

    prompt = f"""
    Tu es le rédacteur en chef cynique, théâtral et passionné de "La Gazette Galactique", le journal officiel (mais délicieusement partial) de notre partie de jeu 4X (Tour {tour_id} en cours). 
    
    Ton objectif est de rédiger l'édition du jour en direct de la galaxie, en te basant uniquement sur l'historique du Tour 1 jusqu'à ce Tour {tour_id}.
    
    ### Données structurées du JSON global :
    - `tour` : numéro actuel.
    - `joueurs` : liste des commandants (`joueur`, `race`, `alliance`, `isolement` [0.0 = ultra-connecté/allié à 1.0 = ermite/paria], `indicateurs_clefs`, `fait_marquant_outliers`, `evenements_du_tour`, `historique_et_seuils`).
    - `matrice_relations_historiques` : volumes cumulés et fréquences de toutes les paires depuis le Tour 1.
    - `indices_complots_suspects` : alertes de convergence militaire ou transaction occulte. (Si la liste est `[]`, n'invente aucune alerte).

    ### Directives de Rédaction & Ton
    1. **Raconter au présent :** Actualité brûlante du Tour {tour_id}. Utilise l'historique récent sans jamais faire allusion au futur.
    2. **Journalisme paranoïaque :** Plonge dans la `matrice_relations_historiques` et les `indices_complots_suspects`. Si une alerte est présente, **tu DOIS en faire le sujet principal de ta Une ou de ta chronique géopolitique**. Accuse publiquement les coupables de pacte occulte (interdiction d'invoquer le hasard). Si `indices_complots_suspects` est vide, ne fabrique pas de faux soupçons.
    3. **Exploitation globale :** Raconte les combats, analyse les flux de ressources (dons, racket) et raille les scores d'isolement.
    4. **Inclusivité :** Varie les angles et cite au moins un tiers des commandants (via articles ou brèves).

    ### Structure de la Gazette :
    1. **La Une (Titre choc & édito) :** L'événement majeur, le choc militaire ou le complot du tour.
    2. **Chronique des Armes et du Sang :** Récit des affrontements, pertes de territoires et sorts des lieutenants.
    3. **Le Carnet Noir & Blanc (Dons, Alliances & Réseau) :** Analyse de la carte politique, des scores d'isolement et des alliances de fait repérées via la matrice historique.
    4. **Le Baromètre des Streaks et des Records :** Focus sur les séries en cours et les seuils franchis.
    5. **Les Brèves du Vide :** Mentions éclair (1-2 phrases max) pour couvrir le reste des commandants.

    ### RÈGLES DE RÉDACTION STRICTES :
    - **Pas de chiffres bruts** : Transforme-les en récits ou rumeurs.
    - **Bannissement du jargon technique** : Interdiction de citer *outliers*, *dérivée*, *isolation forest*, *score d'isolement*, *ATH* ou *JSON*. Traduis-les en lore (ex: "ermite reclus" ou "plaque tournante diplomatique").
    - **Phrases courtes et percutantes** dans les brèves.

    Données JSON du Tour {tour_id} :
    {joueurs_json_str}
    """

    response = model.generate_content(prompt)
    return response.text

def envoyer_messages_multiples_discord(liste_messages):
    if not DISCORD_WEBHOOK_URL:
        print("[DISCORD] URL du webhook non configurée.")
        return

    for i, msg in enumerate(liste_messages, 1):
        if not msg.strip():
            continue
        TAILLE_MAX = 1950
        morceaux = [msg[j:j+TAILLE_MAX] for j in range(0, len(msg), TAILLE_MAX)]
        for k, morceau in enumerate(morceaux, 1):
            payload = {"content": morceau}
            try:
                response = requests.post(DISCORD_WEBHOOK_URL, json=payload)
                if response.status_code == 204 or response.ok:
                    print(f"[DISCORD] Message {i} (partie {k}/{len(morceaux)}) envoyé.")
                else:
                    print(f"[DISCORD] Erreur d'envoi : {response.status_code} - {response.text}")
            except Exception as e:
                print(f"[DISCORD] Exception : {e}")

def save_to_sheet(sh, worksheet_name, rows, headers):
    try:
        ws = sh.worksheet(worksheet_name)
        sh.del_worksheet(ws)
    except gspread.exceptions.WorksheetNotFound:
        pass
    ws = sh.add_worksheet(title=worksheet_name, rows=max(len(rows) + 5, 50), cols=max(len(headers) + 5, 55))
    ws.append_row(headers)
    if rows:
        ws.append_rows(rows)

def main():
    print("--- DÉBUT DU PIPELINE ---")
    tours = get_latest_turns_and_download()
    if not tours:
        return

    historique_tours = {t: parse_tour_files(t) for t in tours}
    dernier_tour_dict_enrichi = compiler_indicateurs_avances_et_seuils(historique_tours)

    sh = gc.open(SHEET_NAME)
    print(f"Connecté avec succès au Google Sheet : {SHEET_NAME}")

    # 1. RAW DATA
    parsed_rows = []
    for jid, data in dernier_tour_dict_enrichi.items():
        parsed_rows.append([
            int(data.get("tour_id", tours[-1])), str(data.get("joueur_id", jid)),
            str(data.get("nom", "Inconnu")), str(data.get("race", "-")),
            int(data.get("planetes", 0)), float(data.get("centaures", 0.0)),
            float(data.get("pop", 0.0)), float(data.get("puissance", 0.0)),
            float(data.get("reputation", 0.0)), float(data.get("tech_points", 0.0)),
            float(data.get("rayonnement_pts", 0.0)), float(data.get("popvs_pts", 0.0)),
            float(data.get("offensive_pts", 0.0))
        ])
    save_to_sheet(sh, "RAW_DATA", parsed_rows, ["Tour_ID", "Joueur_ID", "Nom", "Race", "Planetes", "Centaures", "Pop", "Puissance", "Reputation", "Tech_Points", "Rayonnement_Pts", "PopVS_Pts", "Offensive_Pts"])

    # 2. ANALYSIS RESULTS (Conservé)
    analysis_rows = []
    for jid, data in dernier_tour_dict_enrichi.items():
        ind_derives = data.get("indicateurs_derives", {})
        ind_militaires = data.get("indicateurs_militaires", {})
        ind_geo = data.get("indicateurs_geopolitiques", {})

        def g(metrique):
            m_dict = ind_derives.get(metrique, {})
            return [
                float(m_dict.get("progression", 0.0)), float(m_dict.get("derivee_progression", 0.0)),
                float(m_dict.get("ecart_type", 0.0)), float(m_dict.get("ecart_moyenne", 0.0)),
                float(m_dict.get("all_time_high", 0.0)), float(m_dict.get("all_time_low", 0.0)),
                int(m_dict.get("tours_consecutifs_haut", 0))
            ]

        row_data = [int(data.get("tour_id", tours[-1])), str(data.get("joueur_id", jid)), str(data.get("nom", "Inconnu")), str(data.get("race", "-"))]
        for met in ["puissance", "planetes", "pop", "centaures", "reputation", "tech_valeur", "rayonnement_pts", "popvs_pts", "offensive_valeur", "impact"]:
            row_data.extend(g(met))

        cibles_list = data.get("combats", {}).get("cibles_attaquees", [])
        cibles_str = ", ".join(map(str, cibles_list)) if cibles_list else ""
        dons_list = [f"{d.get('type_don')} vers {d.get('receveur_nom')}" for d in data.get("dons_emis", [])]
        dons_str = ", ".join(dons_list) if dons_list else ""

        row_data.extend([
            int(ind_militaires.get("balance_projection", 0)), int(ind_militaires.get("attaques_lancees", 0)),
            int(ind_militaires.get("attaques_subies", 0)), float(ind_militaires.get("indice_tension", 0.0)),
            float(ind_militaires.get("ratio_offensif", 0.0)), str(ind_geo.get("alliance", "Aucune")),
            float(ind_geo.get("est_isole", 1.0)), str(data.get("stat_alerte", "stable")),
            cibles_str, dons_str, int(data.get("cumul_technologies_donnees", 0)),
            int(data.get("cumul_technologies_recues", 0)), float(data.get("cumul_centaures_donnes", 0.0)),
            float(data.get("cumul_centaures_recus", 0.0)), int(data.get("cumul_planetes_prises", 0)),
            int(data.get("cumul_planetes_perdues", 0)), int(data.get("cumul_lieutenants_achetes", 0)),
            int(data.get("cumul_lieutenants_morts", 0)),
            float(data.get("cumul_centaures_depenses_lieutenants", 0.0)),
            *[int(data.get(streak, 0)) for streak in STREAKS]
        ])
        analysis_rows.append(row_data)

    headers = ["Tour_ID", "Joueur_ID", "Nom", "Race"]
    for met in ["Puis", "Plan", "Pop", "Cent", "Rep", "Tech", "Ray", "PopVS", "Off", "Impact"]:
        headers.extend([f"{met}_Prog", f"{met}_Deriv", f"{met}_Std", f"{met}_EcartMoy", f"{met}_ATH", f"{met}_ATL", f"{met}_ToursHaut"])
    headers.extend(["Mil_BalanceProj", "Mil_AttAtq", "Mil_AttSub", "Mil_IndiceTension", "Mil_RatioOff", "Geo_Alliance", "Geo_EstIsole", "Statut_Alerte", "Commandants_Attaques", "Dons_Emis", "Cumul_Technologies_Donnees", "Cumul_Technologies_Recues", "Cumul_Centaures_Donnes", "Cumul_Centaures_Recus", "Cumul_Planetes_Prises", "Cumul_Planetes_Perdues", "Cumul_Lieutenants_Achetes", "Cumul_Lieutenants_Morts", "Cumul_Centaures_Depenses_Lieutenants", *[streak.title() for streak in STREAKS]])

    save_to_sheet(sh, "analysis_results", analysis_rows, headers)

    # 3. Génération, LOG et écriture JSON des joueurs dans 'narrative_outputs'
    joueurs_json_list = generer_structs_json_joueurs_avancees(dernier_tour_dict_enrichi)
    matrice_relations_historiques = construire_matrice_relations_historiques(historique_tours)
    indices_complots_suspects = detecter_indices_complots_suspects(historique_tours)

    print("\n[LOG] Contenu du JSON généré pour les joueurs :")
    payload_complet = {
        "tour": tours[-1],
        "joueurs": joueurs_json_list,
        "matrice_relations_historiques": matrice_relations_historiques,
        "indices_complots_suspects": indices_complots_suspects
    }
    payload_complet_str = json.dumps(payload_complet, ensure_ascii=False, indent=2)
    print(payload_complet_str)

    narrative_rows = []
    for j_json in joueurs_json_list:
        narrative_rows.append([j_json.get("joueur"), json.dumps(j_json, ensure_ascii=False)])

    save_to_sheet(sh, "narrative_outputs", narrative_rows, ["Joueur", "Payload_JSON"])
    print("[Succès] Structures JSON narratives écrites dans la feuille 'narrative_outputs'.")

    # 4. APPEL IA AVEC LE FICHIER JSON EN INPUT
    
    print("\n[IA] Gazette lancée à partir du JSON.")
    texte_gazette = generer_gazette_ia(payload_complet_str, tours[-1])
    envoyer_messages_multiples_discord([
        f"🚀 **[Tour {tours[-1]}] Analyse terminée. Diffusion de la gazette...**",
        texte_gazette
    ])
    print("--- PIPELINE TERMINÉ AVEC SUCCÈS ---")

if __name__ == "__main__":
    main()
